modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="pyromancer" #mandatory
version="2.0.0"
displayName="Pyromancer" #mandatory
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.pyromancer]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pyromancer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
