modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License, version 3"
[[mods]]
modId="pyromancer" #mandatory
version="2.0.0"
displayName="Pyromancer" #mandatory
credits="" #optional
authors="nikgub_" #optional
description='''
'''
[[dependencies.pyromancer]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pyromancer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pyromancer]]
    modId="incandescent_lib"
    mandatory=true
    versionRange="[1.0,1.1)"
    ordering="NONE"
    side="BOTH"
